name: Deploy RouteFinderApp

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Config File
        run: |
          if [ -f config.template.js ]; then
            cp config.template.js config.js
            sed -i "s/MAPBOX_TOKEN_PLACEHOLDER/${{ secrets.MAPBOX_API_KEY }}/g" config.js
            sed -i "s/GEOAPIFY_TOKEN_PLACEHOLDER/${{ secrets.GEOAPIFY_API_KEY }}/g" config.js
            
            sed -i '/config.js/d' .gitignore
          else
            echo "Error: config.template.js not found!"
            exit 1
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: false
