name: Deploy RouteFinderApp

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Config File
        run: |
          cp config.template.js config.js
          sed -i "s/MAPBOX_TOKEN_PLACEHOLDER/${{ secrets.MAPBOX_API_KEY }}/g" config.js
          sed -i "s/GEOAPIFY_TOKEN_PLACEHOLDER/${{ secrets.GEOAPIFY_API_KEY }}/g" config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
